### ISSUE TITLE
How to predict with a BioImageIO model using Python API

### ISSUE THREAD

**Issue by ElpadoCan** [bioimage-io/core-bioimage-io-python#439]
Is there an example where I can see how to run prediction with my own data using Python API? I used to use `bioimageio.core.load_resource_description`, `bioimageio.core.create_prediction_pipeline`, and `bioimage.io.core.predict_with_padding` but I'm not sure they are still valid options. 

In general, I would like to maintain my package so that it can run models with the latest APIs. 

Additionally, how would one specify additional parameters for the model? For example, if I download [cellpose cyto3](https://bioimage.io/#/?tags=cellpose&id=famous-fish) using `load_resource_description` how do I specify the [`diameter`](https://cellpose.readthedocs.io/en/latest/api.html#cellpose.models.Cellpose) parameter? Thanks!

**Comment by oeway** [comment]
Hi @ElpadoCan maybe look at this notebook: https://github.com/bioimage-io/core-bioimage-io-python/blob/main/example/model_usage.ipynb

cc @FynnBe

**Comment by FynnBe** [comment]
> I used to use[...]

`bioimageio.core.load_resource_description` and `bioimageio.core.create_prediction_pipeline`

This approach is still up-to date 👍 

`bioimage.io.core.predict_with_padding` has been replaced by `bioimageio.core.predict` which has appropriate kwargs: https://bioimage-io.github.io/core-bioimage-io-python/bioimageio/core.html#predict

> Hi @ElpadoCan maybe look at this notebook: https://github.com/bioimage-io/core-bioimage-io-python/blob/main/example/model_usage.ipynb

Thanks @oeway for this, this example is up-to-date as well showcasing both approaches.

> Additionally, how would one specify additional parameters for the model? For example, if I download [cellpose cyto3](https://bioimage.io/#/?tags=cellpose&id=famous-fish) using load_resource_description how do I specify the [diameter](https://cellpose.readthedocs.io/en/latest/api.html#cellpose.models.Cellpose) parameter?

There is no model-independent way to do this as of now and additional non-tensor parameters are not included in the input spec yet. (It is likely that we'll add this, especially if the community asks for it ;-) ). 
If you are using the pytorch_state_dict weights, model specific kwargs may be exposed.
These can be accessed and modified under `model.weights.pytorch_state_dict.architecture.kwargs`

Maybe @mese79 (who uploaded the model) can chime in on this, maybe `diam_mean` is what you're looking for?

Here are the model specific kwargs from the raw description for reference:
```yaml
weights:
  pytorch_state_dict:
    architecture:
      callable: CellPoseWrapper
      kwargs:
        cellprob_threshold: 0.0
        channels: [0, 0]
        cp_batch_size: 8
        diam_mean: 30.0
        do_3D: false
        estimate_diam: true
        flow_threshold: 0.4
        gpu: true
        normalize: true
        stitch_threshold: 0.0
```
